### ISSUE TITLE
Can't see anything in the question preview

### ISSUE THREAD

**Issue by mudrd8mz** [LearningScience/moodle-qtype_lsciss#1]
Not sure if I am doing something wrong, but this is all I can see when previewing the question. Note the "Hello" text comes from a section cell, but all those "\n" are suspicious.

![image](https://cloud.githubusercontent.com/assets/85831/16295977/3175d33a-392a-11e6-97f6-aa61c529f966.png)

**Comment by josh-newton** [comment]
Sorry, I'm having trouble replicating this. Would you be able to send me the content from your spreadsheet json textarea (just below the spreadsheet), then i'll be able test with the same spreadsheet layout as you. I'm thinking the "\n" is coming from an input not being escaped correctly.
